name: 'Vcpkg CI'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04']
        include:
          - os: 'windows-2019'
            triplet: 'x86-windows'
            mono: ''
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            mono: 'mono'
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'

      - name: 'Install vcpkg on Ubuntu'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          git submodule update --init
          ./vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: 'Install vcpkg on Windows'
        if: matrix.os == 'windows-2019'
        run: |
          git submodule update --init
          .\vcpkg\bootstrap-vcpkg.bat
        shell: powershell

      - name: 'Setup NuGet Credentials'
        run: |
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/moratom/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "moratom" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/moratom/index.json"
        shell: bash

      - name: 'vcpkg package restore'
        run: ./vcpkg/vcpkg install sqlite3 cpprestsdk --triplet ${{ matrix.triplet }}
        shell: bash
